# Generated by Django 5.0 on 2024-05-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
